# permissions for end users to edit clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: client-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-frp-operator
    app.kubernetes.io/part-of: k8s-frp-operator
    app.kubernetes.io/managed-by: kustomize
  name: client-editor-role
rules:
- apiGroups:
  - frps.ak1l.de.frps.ak1l.de
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frps.ak1l.de.frps.ak1l.de
  resources:
  - clients/status
  verbs:
  - get
