# permissions for end users to view upstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upstream-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-frp-operator
    app.kubernetes.io/part-of: k8s-frp-operator
    app.kubernetes.io/managed-by: kustomize
  name: upstream-viewer-role
rules:
- apiGroups:
  - frps.ak1l.de.frps.ak1l.de
  resources:
  - upstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frps.ak1l.de.frps.ak1l.de
  resources:
  - upstreams/status
  verbs:
  - get
